apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-iii
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii
        tier: frontend
    spec:
      containers:
      - image: fireflyiii/core:version-6
        name: firefly-iii
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: app_key
        - name: DB_HOST
          value: firefly-iii-mysql
        - name: DB_CONNECTION
          value: mysql
        - name: DB_DATABASE
          value: "fireflyiii"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: db_password
        - name: STATIC_CRON_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: static_cron_token
        - name: TRUSTED_PROXIES
          value: "**"
        - name: TZ
          value: Europe/Berlin
        - name: SEND_ERROR_MESSAGE
          value: "true"
        - name: SEND_REPORT_JOURNALS
          value: "true"
        - name: APP_URL
          value: http://firefly.local
        envFrom:
        - secretRef:
            name: email-sender-secret
        ports:
        - containerPort: 8080
          name: firefly-iii
        volumeMounts:
        - mountPath: "/var/www/html/storage/upload"
          name: firefly-iii-upload 
        imagePullPolicy: Always
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-iii-upload-claim
