apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: firefly-iii
    tier: frontend
