---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: firefly-iii
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAFDZ2R2NP966rDDu9s8g3RwAzTjBqJilJvzXEEIsCbxx5h1pO4wfGYCmo2tWG6owT4S28WoKk/XRpzqL7sUDgx1H84IMC/yMQf73qQ/R2qliOKobbqkTQPCXai+xRPLWQRzVBQZ2x7CkzZZesSNgYG0k6IvGdyPzfML5EFiW3NKzRZ3fSTqteLtNUkTdZdp7d3ZiA5ZcCSMDnXqwGD/syHWuCjmdccIbUcJeiRq89lKnLb2yJsXfX6FpufwnR+zc9pX+qC2F5/6MaGW0KIP12RnbQ0lZ4de2Y5ugOS979NJp11sajSJBAIBGM6JoRa0/ZFX3lEChUZXympwKsR0Y4WTo9SfZXkVqclz8C+iPy+KKHdKuinL3NEoHMbzLvum7JukmZPx92PzTdn2Kt4LTHtBx/Q09DsojarnYvLsiIA7O96N6Z3F29OkjdgW51OohxRRuSxj/ldEOeDfkqx7+sdGllw9+l75ewfBHorh91nqCT7AVCnk6Lgd/XaMcKJJneN4tzFlOR78NcFeQPXlerJyb5I0j1owzCbUhJN6hXuLy5DYndfCIVzbOCeP4G/rI+xt9uvsZJMi0JDBdHM9JZSwMbGtKCd3Iq+W87SLJVyvF4LluQmpUi3+s1n9dZsaei/AL3Q4KS6SNrVE26xAMIImr/Yzj43x53S6LUrGlPQh4YaYCzbXCDmnAKi+N/9TDq9AR2Hh4ZtcV72OGSSeBhS1e5ZRB32FBYY/jEo3SLIZhoD
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: firefly-iii
